version: '3.4'

services:
  microservice.httpa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  microservice-httpa-dapr:
    command: ["./daprd",
      "-app-id", "httpa",
      "-app-port", "80"
      ]
  microservice.httpb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  microservice-httpb-dapr:
    command: ["./daprd",
      "-app-id", "httpb",
      "-app-port", "80"
      ]

  microservice.grpca:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  microservice-grpca-dapr:
    command: ["./daprd",
      "-app-id", "grpca",
      "--app-protocol","grpc",
      "-app-port", "443",
      "--app-ssl","true"     
      ]
  microservice.grpcb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  microservice-grpcb-dapr:
    command: ["./daprd",
      "-app-id", "grpcb",
      "--app-protocol","grpc",
      "-app-port", "443",
      "--app-ssl","true"
      ]
